kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: tomcat-read-config
roleRef:
  kind: Role #this must be Role or ClusterRole # this must match the name of the
  # Role or ClusterRole you wish to bind to 
  name: read-config
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: tomcat # Name is case sensitive
  namespace: default
