kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-config
  namespace: default
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
