apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  namespace: resource-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: harbor.prodyna.com/training/tomcat-sample:oteichmann
        env:
        - name: STATIC_VAR
          value: "Hello from environment"
        - name: COLOR
          value: "#a0c52a"  
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "0.5Gi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe: 
          failureThreshold: 2
          httpGet:
            path: /tomcat-sample
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 5  