apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limit-range
  namespace: resource-test
spec:
  limits:
    - type: Container
      default:
        memory: 128Mi
        cpu: 500m
      defaultRequest:
        memory: 64Mi
        cpu: 100m
      max:
        memory: 2Gi