apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: harbor.prodyna.com/training/tomcat-sample:oteichmann
        env:
        - name: STATIC_VAR
          value: "Hello from environment"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-restriction.kubernetes.io/my-label
                  operator: In
                  values:
                    - worker-1
      tolerations:
        - key: foo
          operator: Exists
          effect: NoSchedule